Fix DSN string construction for Windows Access ODBC driver, template candidate preference order
OSGeo/gdal pull request #2878
Opened 2020-08-20 23:10 UTC by nyalldawson

The Windows ODBC driver does not like quoted filenames, yet the UnixODBC driver requires these (for filenames with spaces). So
ifdef the expected formats for the corresponding platforms. Follow up https://github.com/OSGeo/gdal/pull/2837

Also flip the order of the candidate DSN string templates, to try the more common/modern "Microsoft Access Driver (*.mdb, *.accdb)" driver name first.

2020-08-21 07:50 UTC, rouault commented
We have a fair amount of copy & paste between all those drivers. I'm wondering if some sort of utility functions/class in ogr/ogrsf_frmts/odbc/ couldn't be added and used by all those drivers ?

2020-08-24 07:10 UTC, nyalldawson commented
@rouault how's the new version?

2020-08-25 08:52 UTC, rouault requested changes
Thanks. A few changes needed to make linting happy

2020-08-25 08:52 UTC, rouault commented on gdal/port/cpl_odbc.cpp
> +        return FALSE;
```suggestion
        return false;
```

2020-08-25 08:52 UTC, rouault commented on gdal/port/cpl_odbc.cpp
> +    return TRUE;
```suggestion
    return true;
```

2020-08-25 08:52 UTC, rouault commented on gdal/port/cpl_odbc.cpp
> +
Doxygen comment needed

2020-08-25 08:52 UTC, rouault commented on gdal/port/cpl_odbc.cpp
> +    pszDSN = (char *) CPLMalloc(strlen(pszName)+strlen(pszDSNStringTemplate)+100);
code in port/ no longer allows C style casts. So either use static_cast<char*> (here and at line 451). Or just go for std::string

2020-08-25 21:32 UTC, nyalldawson commented
Ok, updated. In the new function dox I used "@since 3.2", but these changes should be backported in order to fix the regression introduced by #2837

2020-08-25 22:29 UTC, rouault commented
on OSX:
```
 ogr/ogr_odbc.py::test_ogr_odbc_1 SKIPPED                                 [ 15%]
./gdal/ci/travis/osx/script.sh: line 17: 80569 Segmentation fault: 11  $PYTEST
ogr/ogr_odbc.py::test_ogr_odbc_2 
```

```
ogr/ogrsf_frmts/pgeo/ogrpgeodatasource.cpp:111,style,redundantAssignment,Variable 'pszDSN' is reassigned a value before the old one has been used.
ogr/ogrsf_frmts/walk/ogrwalkdatasource.cpp:76,style,redundantAssignment,Variable 'pszDSN' is reassigned a value before the old one has been used.
```

2020-08-25 23:10 UTC, nyalldawson commented
@rouault fixed

2020-08-26 00:40 UTC, nyalldawson commented
@rouault is there anyway to get more detailed debugging as to why the odbc test is failing on windows? I can't reproduce this locally on my Windows build...

2020-08-26 17:35 UTC, rouault commented
> is there anyway to get more detailed debugging as to why the odbc test is failing on windows?

you may try to add a manual `pytest ogr_odbc.py --capture=no -ra -vv` with `set CPL_DEBUG=ON` set before. You may need to instrument with extra debug messages

2020-08-29 17:28 UTC, rouault commented
Note: if there is no resolution for this before next Tuesday where I'll cut a 3.1.3 RC, I'll have to revert 1f71651d6bfda5a76dd7a449cc45dbf5022ec152 in 3.1 branch since I understand it causes a regression.

2020-08-31 02:32 UTC, nyalldawson commented
@rouault 
48ae0cb should fix this -- the github Windows build workflow only has the older Access ODBC driver available, which doesn't support reading accdb database files

2020-08-31 08:09 UTC, merged

2020-08-31 08:51 UTC, rouault commented
Backported to 3.1 in e2c83edf7862ae3c035c17fba3bf9abf6ad3aec9 (without the new tests that depend on test files not backported)