NITF: Add hexadecimal TRE creation
OSGeo/gdal pull request #3049
Opened 2020-10-10 01:49 UTC by matthew-baran

## What does this PR do?
This PR adds a NITF creation option to create TREs from a hexadecimal string.

Several TREs defined in the Spectral NITF Implementation Profile have non-string fields (uint, float32, etc).  This capability will help develop more effective tests of SNIP TREs.

The SNIP is in NGA.STND.0072_1.0_SNIP 7 June 2019.

## What are related issues/pull requests?
https://github.com/OSGeo/gdal/pull/2983
## Tasklist

 - [ ] ADD YOUR TASKS HERE
 - [ ] Add test case(s)
 - [ ] Add documentation
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS:
* Compiler:

2020-10-10 10:05 UTC, rouault requested changes
Python2-based autotests (sorry we still support it for now) complain:
```
   def test_nitf_78():
>       float_data = struct.pack(">f", 2.1).hex()
E       AttributeError: 'str' object has no attribute 'hex'
```
I would perhaps suggest to put the resulting binary content directy with a comment that it is the result of struct.pack(">f", 2.1).hex()

2020-10-10 10:05 UTC, rouault commented on gdal/frmts/nitf/nitffile.c
> +                return FALSE;
missing
```
CPLFree( pszTREName);
CPLFree( pszUnescapedContents );
```

2020-10-11 01:59 UTC, matthew-baran commented on gdal/frmts/nitf/nitffile.c
> +                return FALSE;
ack - good catch

2020-10-11 02:02 UTC, matthew-baran commented
> 
> 
> Python2-based autotests (sorry we still support it for now) complain:
> 
> ```
>    def test_nitf_78():
> >       float_data = struct.pack(">f", 2.1).hex()
> E       AttributeError: 'str' object has no attribute 'hex'
> ```
> 
> I would perhaps suggest to put the resulting binary content directy with a comment that it is the result of struct.pack(">f", 2.1).hex()

Roger that - Made a local environment for Python 2 testing as well.

2020-10-12 14:29 UTC, rouault commented on gdal/frmts/nitf/nitffile.c
> +            char pszSubStr[2];
```suggestion
            char pszSubStr[3];
```
to fix
```
=13636==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffe67a558f2 at pc 0x7f087a3ffac2 bp 0x7ffe67a557b0 sp 0x7ffe67a557a8
WRITE of size 1 at 0x7ffe67a558f2 thread T0
    #0 0x7f087a3ffac1 in CPLStrlcpy /home/travis/build/OSGeo/gdal/gdal/port/cpl_string.cpp:2720:18
    #1 0x7f087867f832 in NITFWriteTREsFromOptions /home/travis/build/OSGeo/gdal/gdal/frmts/nitf/nitffile.c:1359:17
```

2020-10-12 16:11 UTC, rouault commented
doc/source/drivers/raster/nitf_advanced.rst should likely be updated to explain that new capability

2020-10-12 18:07 UTC, rouault commented on gdal/doc/source/drivers/raster/nitf_advanced.rst
> +::
```suggestion
.. code-block:: python
```

2020-10-12 18:16 UTC, rouault approved these changes

2020-10-12 20:06 UTC, merged