RFC77: Py3 miscellaneous updates
OSGeo/gdal pull request #3241
Opened 2020-11-27 11:24 UTC by rcoup

## What does this PR do?

1. Stop looking for `python` and `python2` in `configure`, just find `python3`
2. Similar for `setdevenv.sh`
3. Switch shebang lines in scripts from `/usr/bin/env python` → `/usr/bin/env python3`
4. Update Python invocations in scripts from `python` → `python3`
4. Update `python` → `python3` in docs

## What are related issues/pull requests?

[RFC77](https://gdal.org/development/rfc/rfc77_drop_python2_support.html)

/cc @idanmiara 

## Tasklist

- [ ] `gdal/swig/python/README.rst` could probably do with a wider review/update — I'm not sure any the setuptools/binary egg stuff is still relevant/working?
- [ ] `ci/travis/*` I haven't touched, I think travis is imminently going away, so maybe not worth the effort?
- [ ] `swig/python/fallback_build.bat` & `swig/python/fallback_build_mingw32_under_unix.sh` — not sure what these are doing/needed for
- [ ] `gdal/doc/source/drivers/raster/vrt.rst` & `gdalpython.cpp` → separate PR.

 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

2020-11-27 11:26 UTC, rcoup commented
(This started out by `setdevenv.sh` finding python2 even though I'd set `--with-python=python3`...)

2020-11-27 12:30 UTC, rouault commented on gdal/swig/python/fallback_build_mingw32_under_unix_py37.sh
> +wine "$PYTHONHOME/python3" setup.py build
should be reverted as the cause of the failure for the mingw_w64 CI job. The windows Python 3.7 install probably only ships python.exe

2020-12-19 07:36 UTC, avalentino requested changes

2020-12-19 07:36 UTC, avalentino commented on gdal/nmake.opt
> +PYEXEC = python3.exe
This could be related to the @rouault comment (https://github.com/OSGeo/gdal/pull/3241/files#r531574726), please check.

2021-01-17 22:03 UTC, closed without merging