NITF: Adds ability to export RPC parameters as SensorML2 docs (Attempt 2)
OSGeo/gdal pull request #3358
Opened 2021-01-08 12:25 UTC by ghobona

This commit adds to GDAL an ability to export Rational Polynomial Coefficients (RPC) parameters as a SensorML2 document.

To support this capability, a function `GDALWriteRPCSensorMLFile` has been added to `gdal_mdreader.cpp`, specified in `gdal_mdreader.h`. The function is called from `nitfdataset.cpp`.

To invoke the function, an example call is below.

`gdal_translate -of NITF -co RPCTXT=YES  /Users/geo/rpc_sample.ntf /Users/geo/out_rpc_out.ntf`

The code was tested using a NITF file created from the GeoTIFF files at https://www.isprs.org/data/ikonos/default.aspx

A copy of the generated SensorML2 file is [here](https://github.com/opengeospatial/ets-sensorml20/blob/master/src/test/resources/nitf_rpc_sensorml2.xml)

2021-01-08 16:01 UTC, rouault requested changes
We would also need a test in autotest/gdrivers/nitf.py

2021-01-08 16:01 UTC, rouault commented on gdal/gcore/gdal_mdreader.cpp
> +/*                         GDALWriteRPCSensorMLFile()                        */
extra spaces

2021-01-14 23:27 UTC, ghobona commented on gdal/gcore/gdal_mdreader.cpp
> +  CPLString osRPCFilename = pszFilename;
I noticed that there is a clang-format configuration in the scripts folder.

Are you happy for me to run clang-format over the **gdal/gcore/gdal_mdreader.cpp** file?

2021-01-14 23:33 UTC, ghobona commented on gdal/gcore/gdal_mdreader.cpp
> +  CPLString osRPCFilename = pszFilename;
Perhaps, instead, I can just run clang-format over the new function only.

2021-01-15 11:52 UTC, rouault commented on gdal/gcore/gdal_mdreader.cpp
> +  CPLString osRPCFilename = pszFilename;
> I can just run clang-format over the new function only.

yes please.

2021-01-19 20:00 UTC, ghobona commented on gdal/gcore/gdal_mdreader.cpp
> +/*                         GDALWriteRPCSensorMLFile()                        */
Done

2021-01-19 20:05 UTC, ghobona commented on gdal/gcore/gdal_mdreader.cpp
> +  CPLString osRPCFilename = pszFilename;
I managed to apply clang-format on the function. So the `gdal_mdreader.cpp` file is now done.

However, I was unable to add a test into `autotest/gdrivers/nitf.py`. I will have to let someone else with more familiarity of `autotest/gdrivers/nitf.py` implement the test.

2021-02-01 21:41 UTC, ghobona commented
@alexrobin  I have created this PR to enable GDAL to export SensorML2 representing RPC00B fields from a NITF file. Could you please peer-review the SensorML2 generated? 

I would appreciate your feedback.

Sample output is attached.
[out_rpc_RPC_SML.zip](https://github.com/OSGeo/gdal/files/5906927/out_rpc_RPC_SML.zip)

2021-02-02 14:03 UTC, ghobona commented
@alexrobin @rouault 

I have received some feedback from another project. The new plan is to coordinate the PR with another activity happening elsewhere. So I am closing this PR and will open a new one when ready to resubmit.

2021-02-02 14:03 UTC, closed without merging