JAVA: Expose two new methods for GDAL's JNI Bridge
OSGeo/gdal pull request #3611
Opened 2021-03-25 23:00 UTC by mglazer

## What does this PR do?

Exposes two new JNI methods. Specifically:

* VSIFileFromMemBuffer - Augments to support taking a ByteBuffer as an
  argument
* VSIGetMemFileFromBuffer - Exposes this method and returns a ByteBuffer
  pointer to the underlying memory.

## What are related issues/pull requests?

n/a, just exposing what could have been exposed from the start. This is my first gdal contribution as well as some of the first swig code I've written so apologies if I did anything incorrectly.

## Tasklist

 - [ ] ADD YOUR TASKS HERE
 - [ ] Add test case(s)
 - [ ] Add documentation
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS:
* Compiler:

2021-03-26 12:06 UTC, rouault requested changes

2021-03-26 12:06 UTC, rouault commented on gdal/swig/include/cpl.i
> +void wrapper_VSIFileFromMemBuffer( const char* utf8_path, void* nioBuffer, long nioBufferSize) {
This method is already available in the Java case a bit above. Are we sure that the 2 can co-exist ? Adding a test program in swig/java/apps/ checking  that both work would be needed

2021-03-26 12:06 UTC, rouault commented on gdal/swig/include/cpl.i
> +jobject wrapper_VSIGetMemFileBuffer(JNIEnv *jenv, const char* utf8_path) {
hum I don't think that playing directly with JNIEnv* here is the most idiomatic way of proceeding. Ideally we should minimize the amount of language specificities here. A cleaner way would probably to have something like
void wrapper_VSIGetMemFileBuffer(const char* utf8_path, void** outBuffer, size_t* outBufferSize) and a typemap for (void** outBuffer, size_t* outBufferSize).

2021-03-26 12:06 UTC, rouault commented on gdal/swig/include/cpl.i
> +    return jenv->NewDirectByteBuffer((void*) result, outBufferLen);
NewDirectByteBuffer() can only work if it is guaranteed that result won't change while the ByteBuffer is in use. There is no such guarantee the /vsimem/ file could be destroyed in-between, or its size grown, causing a realloc(), which would invalidate the original buffer. A copy should be done for safety.
The test program to add mentioned above should also test that.

2021-03-26 12:06 UTC, rouault commented on gdal/swig/include/java/typemaps_java.i
> +%typemap(in, numinputs=0) JNIEnv *jenv %{
that typemap and the one later should probably be removed for other ones, as mentioned above

2021-03-30 22:57 UTC, mglazer commented
Still working through some changes, so not quite there yet. Seems that returning a direct byte buffer really isn't the best thing for a number of reasons (the biggest being that I spend hours trying to get the typemaps to work but couldn't). So ended up just copying the array out, which hopefully is sufficient.

2021-06-20 13:43 UTC, closed without merging