VRT 'if' option for vrt:// connection
OSGeo/gdal pull request #7333
Opened 2023-03-01 03:32 UTC by mdsumner

Adds 'if' (initial format) to the allowed options for a "vrt:// connection.

I've left an open note in the tasklist about

```python
    ds = gdal.Open("vrt://data/float32.tif?if=doesnotexist")
    assert ds is not None
```

should this raise an error or a message? 

## Tasklist

 - [ ] how to test the nominated driver/s are tried, or check if they are invalid ??
 - [x] Add test case(s)
 - [x] Add documentation
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

2023-03-01 12:38 UTC, rouault requested changes

2023-03-01 21:15 UTC, mdsumner commented on frmts/vrt/vrtdataset.cpp
> +                CPLStringList aosInitialFormats(
awesome thank you

2023-03-15 01:04 UTC, mdsumner commented on frmts/vrt/vrtdataset.cpp
> +                CPLStringList aosInitialFormats(
I've done this now, left a note in the OP

2023-03-15 01:08 UTC, mdsumner commented on autotest/gcore/vrt_read.py
> +    ds = gdal.Open("vrt://data/float32.tif?if=AAIGrid,COG")
I've got better tests now :)

2023-03-15 01:13 UTC, rouault commented on frmts/vrt/vrtdataset.cpp
> +    iRemoveOpt = -1;
```suggestion
    CPLStringList aosAllowedDrivers;
    int iRemoveOpt = -1;  // not allowed to have multiple &if=drv1&if=drv2
```

2023-03-15 01:13 UTC, rouault commented on frmts/vrt/vrtdataset.cpp
> +                }
```suggestion
                aosAllowedDrivers = CSLTokenizeString2(pszValue, ",", 0);
```

2023-03-15 01:13 UTC, rouault commented on frmts/vrt/vrtdataset.cpp
> +                          papszAllowedDrivers, nullptr, nullptr);
```suggestion
                          aosAllowedDrivers.List(), nullptr, nullptr);
```

2023-03-15 01:13 UTC, rouault commented on frmts/vrt/vrtdataset.cpp
> +                             "multiple times (use comma separated list)\n");
```suggestion
                    CPLError(CE_Failure, CPLE_IllegalArg,
                             "Invalid vrt:// 'if' format, must not occur "
                             "multiple times (use comma separated list)\n");
                    return nullptr;
```

2023-03-15 01:23 UTC, rouault commented
you also need to solve the conflict in vrt.rst

2023-03-15 01:38 UTC, rouault approved these changes

2023-03-15 11:03 UTC, merged

2023-03-15 12:11 UTC, mdsumner commented
thanks so much, glad to get this one in - appreciate all the help :) learnt a lot from this one